[theme]
base="dark"
primaryColor="#ccff00"
backgroundColor="#050505"
secondaryBackgroundColor="#111111"
textColor="#e0e0e0"
font="monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
